In [4]:
import pandas as pd

In [2]:
#creating series

In [4]:
pd.Series([10,20,30,40])

0    10
1    20
2    30
3    40
dtype: int64

In [15]:
pd.Series(["luffy","zoro","sanji","nami"],name="luffy crew" ,index= [1,2,3,4])

1    luffy
2     zoro
3    sanji
4     nami
Name: luffy crew, dtype: object

In [16]:
#creating DataFrames

In [22]:
names_list = [ 
    ["luffy",19],
    ["zoro",22],
    ["sanji",22],
    ["nami",20],
]
#pd.DataFrame(names_list)
pd.DataFrame(names_list , columns=["Name","Age"]) #DataFrame from python list

    Name  Age
0  luffy   19
1   zoro   22
2  sanji   22
3   nami   20

In [23]:
names_list_dict = {
    "Names":["luffy","Zoro","Sanj","Nami"],
    "Age":[19,22,22,20]
}
pd.DataFrame(names_list_dict) #Dataframe from python dictionary

   Names  Age
0  luffy   19
1   Zoro   22
2   Sanj   22
3   Nami   20

In [26]:
import numpy as np
arr =  np.array([
    [101,20],
    [102,26],
    [103,34],
    [104,44],
    [105,23]
])
pd.DataFrame(arr,columns=["id","age"]) #DataFrame from numpy array

    id  age
0  101   20
1  102   26
2  103   34
3  104   44
4  105   23

In [2]:
#reading csv file from web

In [5]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [7]:
print(df.head()) #getting only first five rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
print(df.tail()) #getting last five rows

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [9]:
print(df.info()) # Column info: types, non-nulls

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB
None

In [10]:
print(df.describe())

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [12]:
print(df.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [13]:
print(df.shape)

(244, 7)